[package]
name = "kmgr"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
clap = { version = "4.6.1", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["json", "stream"] }
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
anyhow = "1.0.102"
colored = "3.1.1"
toml = "1.1.2"
sha1 = "0.11.0"
sha2 = "0.11.0"
hex = "0.4.3"
futures = "0.3.32"
fslock = "0.2.1"
scraper = "0.27.0"
strsim = "0.11.1"
